"""ExtendScript (.jsx) generator for Premiere Pro multicam sequence creation."""

from __future__ import annotations

import json
from pathlib import PurePosixPath

from autopodcast.models.domain import Timeline


def generate_multicam_jsx(
    xml_path: str,
    timeline: Timeline,
    sequence_name: str,
) -> str:
    """Generate an ExtendScript (.jsx) file for Premiere Pro.

    The script:
    1. Imports the FCP 7 XML via app.project.importFiles().
    2. Searches for the imported sequence by name.
    3. Opens the sequence in the timeline.
    4. Shows detailed instructions (in Russian) for multicam creation.

    Args:
        xml_path: Absolute path to the FCP 7 XML file.
        timeline: Timeline with segments (used for angle switch data).
        sequence_name: Name of the sequence in the XML.

    Returns:
        ExtendScript source code as a string.
    """
    # Build angle switches array for the JSX
    switches = []
    for seg in timeline.segments:
        switches.append({
            "time_s": seg.start_s,
            "camera": seg.camera_index,
        })
    switches_json = json.dumps(switches)

    # Normalize path for ExtendScript (forward slashes)
    xml_posix = PurePosixPath(xml_path).as_posix()

    return f'''\
// AutoPodcast Multicam Setup Script
// Generated by AutoPodcast
// Import this into Premiere Pro via File > Scripts > Run Script

(function() {{
    var xmlPath = "{_escape_js(xml_posix)}";
    var sequenceName = "{_escape_js(sequence_name)}";
    var angleSwitches = {switches_json};

    // Step 1: Import the XML
    var xmlFile = new File(xmlPath);

    if (!xmlFile.exists) {{
        alert("XML file not found:\\n" + xmlPath);
        return;
    }}

    var success = app.project.importFiles([xmlPath]);
    if (!success) {{
        alert("Failed to import XML file:\\n" + xmlPath);
        return;
    }}

    // Step 2: Find the imported sequence
    var seq = null;
    for (var i = 0; i < app.project.rootItem.children.numItems; i++) {{
        var item = app.project.rootItem.children[i];
        if (item.name === sequenceName && item.type === ProjectItemType.SEQUENCE) {{
            seq = item;
            break;
        }}
    }}

    if (!seq) {{
        alert("\\u0421\\u0435\\u043a\\u0432\\u0435\\u043d\\u0446\\u0438\\u044f '" + sequenceName + "' \\u043d\\u0435 \\u043d\\u0430\\u0439\\u0434\\u0435\\u043d\\u0430 \\u0432 \\u043f\\u0440\\u043e\\u0435\\u043a\\u0442\\u0435.\\n" +
              "\\u041d\\u0430\\u0439\\u0434\\u0438\\u0442\\u0435 \\u0435\\u0451 \\u0432\\u0440\\u0443\\u0447\\u043d\\u0443\\u044e \\u0438 \\u0441\\u043e\\u0437\\u0434\\u0430\\u0439\\u0442\\u0435 Multi-Camera Source Sequence.");
        return;
    }}

    // Step 3: Open the sequence in the timeline
    app.project.activeSequence = seq.openSequence ? seq.openSequence() : seq;

    // Step 4: Try to select all clips programmatically
    try {{
        if (typeof qe !== "undefined") {{
            qe.project.getActiveSequence().setPlayerPosition("00;00;00;00");
        }}
    }} catch (e) {{
        // QE DOM not available — ok, manual selection
    }}

    // Step 5: Show instructions
    alert(
        "\\u2705 \\u0421\\u0435\\u043a\\u0432\\u0435\\u043d\\u0446\\u0438\\u044f \\u0438\\u043c\\u043f\\u043e\\u0440\\u0442\\u0438\\u0440\\u043e\\u0432\\u0430\\u043d\\u0430: " + sequenceName + "\\n" +
        "\\u041a\\u0430\\u043c\\u0435\\u0440: 3, \\u0440\\u0430\\u0437\\u0440\\u0435\\u0437\\u043e\\u0432: " + angleSwitches.length + "\\n\\n" +
        "\\u0414\\u043b\\u044f \\u0441\\u043e\\u0437\\u0434\\u0430\\u043d\\u0438\\u044f multicam:\\n\\n" +
        "1. \\u0412\\u044b\\u0434\\u0435\\u043b\\u0438\\u0442\\u0435 \\u0412\\u0421\\u0415 \\u043a\\u043b\\u0438\\u043f\\u044b \\u043d\\u0430 \\u0432\\u0441\\u0435\\u0445 \\u0434\\u043e\\u0440\\u043e\\u0436\\u043a\\u0430\\u0445 (Ctrl+A)\\n" +
        "2. \\u041f\\u041a\\u041c \\u2192 Create Multi-Camera Source Sequence\\n" +
        "3. Sync Point: \\u0432\\u044b\\u0431\\u0435\\u0440\\u0438\\u0442\\u0435 'In Points'\\n" +
        "4. Camera Names: \\u0432\\u044b\\u0431\\u0435\\u0440\\u0438\\u0442\\u0435 'Camera Order'\\n" +
        "5. Audio: \\u0432\\u044b\\u0431\\u0435\\u0440\\u0438\\u0442\\u0435 'All Cameras'\\n\\n" +
        "\\u041f\\u043e\\u0441\\u043b\\u0435 \\u0441\\u043e\\u0437\\u0434\\u0430\\u043d\\u0438\\u044f multicam \\u0441\\u0435\\u043a\\u0432\\u0435\\u043d\\u0446\\u0438\\u0438,\\n" +
        "\\u043e\\u0442\\u043a\\u0440\\u043e\\u0439\\u0442\\u0435 \\u0435\\u0451 \\u0438 \\u0432\\u043a\\u043b\\u044e\\u0447\\u0438\\u0442\\u0435 Multi-Camera\\n" +
        "\\u0432 \\u043c\\u0435\\u043d\\u044e Program Monitor."
    );
}})();
'''


def _escape_js(s: str) -> str:
    """Escape a string for use in a JavaScript string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
